version: '3'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongo_e_shop
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  streamlit:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
